import { createFileRoute } from "@tanstack/react-router";
import { FileDown } from "lucide-react";
import { Button } from "@/components/ui/button";
import { PageHeader } from "@/components/PageHeader";
import { StatCard } from "@/components/ui/stat-card";
import { useEffect, useState } from "react";
import { getReports } from "@/services/adminService";
import { toast } from "sonner";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import FileSaver from "file-saver";

export const Route = createFileRoute("/admin/reports")({
  component: Reports,
});

function Reports() {
  const [stats, setStats] = useState({
    totalUsers: 0,
    totalVolunteers: 0,
    activeAlerts: 0,
    resolvedAlerts: 0,
  });

  useEffect(() => {
  loadStats();
}, []);


  async function loadStats() {
    try {
      const response = await getReports();

      setStats({
        totalUsers: response.data.data.totalUsers,
        totalVolunteers: response.data.data.totalVolunteers,
        activeAlerts: response.data.data.activeAlerts,
        resolvedAlerts: response.data.data.resolvedAlerts,
      });
    } catch (error) {
      console.error(error);
      toast.error("Unable to load Reports");
    }
  }

const exportPDF = () => {
  const doc = new jsPDF();

  const pageWidth = doc.internal.pageSize.getWidth();

  // ===== HEADER =====
  doc.setFillColor(79, 70, 229);
  doc.rect(0, 0, pageWidth, 35, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(24);
  doc.text("SafeHer", pageWidth / 2, 15, {
    align: "center",
  });

  doc.setFontSize(13);
  doc.text("Women Safety Analytics Dashboard", pageWidth / 2, 25, {
    align: "center",
  });

  // ===== Report Details =====
  doc.setTextColor(0);

  doc.setFontSize(11);

  doc.text(
    `Generated On : ${new Date().toLocaleString()}`,
    14,
    48
  );

  doc.text(
    "Generated By : SafeHer Admin Dashboard",
    14,
    56
  );

  doc.setDrawColor(180);
  doc.line(14, 61, 196, 61);

  // ===== Summary =====

  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");

  doc.setTextColor(79,70,229);
doc.text("Platform Summary",14,72);
doc.setTextColor(0);

  autoTable(doc, {
    startY: 78,

    head: [["Metric", "Value"]],

    body: [
      ["Total Users", stats.totalUsers],

      ["Verified Volunteers", stats.totalVolunteers],

      ["Active Alerts", stats.activeAlerts],

      ["Resolved Alerts", stats.resolvedAlerts],
    ],

    theme: "grid",

    headStyles: {
      fillColor: [79, 70, 229],
      halign: "center",
    },

    bodyStyles: {
      halign: "center",
    },
  });
  

  // ===== Insights =====
  const pageHeight = doc.internal.pageSize.getHeight();

const finalY = (doc as any).lastAutoTable.finalY + 20;

  doc.setFont("helvetica", "bold");

  doc.setFontSize(15);

  doc.text("Quick Insights", 14, finalY);

  doc.setFont("helvetica", "normal");

  doc.setFontSize(11);

  doc.text(
    `• Total platform users : ${stats.totalUsers}`,
    18,
    finalY + 10
  );

  doc.text(
    `• Verified volunteers : ${stats.totalVolunteers}`,
    18,
    finalY + 18
  );

  doc.text(
    `• Active emergency alerts : ${stats.activeAlerts}`,
    18,
    finalY + 26
  );

  doc.text(
    `• Successfully resolved alerts : ${stats.resolvedAlerts}`,
    18,
    finalY + 34
  );

  // ===== Footer =====

  doc.setDrawColor(180);

  const footerY = pageHeight - 18;

doc.line(14, footerY, pageWidth - 14, footerY);

  doc.setFontSize(10);

  doc.setTextColor(120);

  doc.text(
    "SafeHer © 2026 | Confidential Admin Report",
    pageWidth / 2,
    footerY + 8,
    {
      align: "center",
    }
  );

  doc.save("SafeHer_Admin_Report.pdf");
  toast.success("PDF Report Downloaded");
};

const exportCSV = () => {
  let csv = "";

  csv += "SAFEHER ADMIN REPORT\n";
  csv += `Generated On,${new Date().toLocaleString()}\n\n`;

  csv += "PLATFORM SUMMARY\n";
  csv += "Metric,Value\n";
  csv += `Total Users,${stats.totalUsers}\n`;
  csv += `Verified Volunteers,${stats.totalVolunteers}\n`;
  csv += `Active Alerts,${stats.activeAlerts}\n`;
  csv += `Resolved Alerts,${stats.resolvedAlerts}\n\n`;

  csv += "Generated by SafeHer Admin Dashboard";

  const blob = new Blob([csv], {
    type: "text/csv;charset=utf-8;",
  });

  FileSaver.saveAs(blob, "SafeHer_Admin_Report.csv");
  toast.success("CSV Report Downloaded");
};

  return (
    <div className="space-y-6">
      <PageHeader
        title="Reports"
        desc="Visual analytics of platform performance."
        action={
          <div className="flex gap-2">
            <Button variant="outline" onClick={exportPDF}>
              <FileDown className="mr-1 size-4" />
              Export PDF
            </Button>

            <Button
  className="gradient-hero text-white"
  onClick={exportCSV}
>
              <FileDown className="mr-1 size-4" />
              Export CSV
            </Button>
          </div>
        }
      />

      <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
        <StatCard
          label="Total Users"
          value={stats.totalUsers.toString()}
        />

        <StatCard
          label="Volunteers"
          value={stats.totalVolunteers.toString()}
          tone="success"
        />

        <StatCard
          label="Active Alerts"
          value={stats.activeAlerts.toString()}
          tone="warning"
        />

        <StatCard
          label="Resolved Alerts"
          value={stats.resolvedAlerts.toString()}
          tone="success"
        />
      </div>
    </div>
  );
}