/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VolunteerRouteImport } from './routes/volunteer'
import { Route as UserRouteImport } from './routes/user'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VolunteerProfileRouteImport } from './routes/volunteer.profile'
import { Route as VolunteerIncidentsRouteImport } from './routes/volunteer.incidents'
import { Route as VolunteerDashboardRouteImport } from './routes/volunteer.dashboard'
import { Route as VolunteerAlertsRouteImport } from './routes/volunteer.alerts'
import { Route as UserSupportTeamsRouteImport } from './routes/user.support-teams'
import { Route as UserSosRouteImport } from './routes/user.sos'
import { Route as UserSafeZonesRouteImport } from './routes/user.safe-zones'
import { Route as UserProfileRouteImport } from './routes/user.profile'
import { Route as UserPredictiveSafetyRouteImport } from './routes/user.predictive-safety'
import { Route as UserLocationRouteImport } from './routes/user.location'
import { Route as UserHistoryRouteImport } from './routes/user.history'
import { Route as UserDashboardRouteImport } from './routes/user.dashboard'
import { Route as UserContactsRouteImport } from './routes/user.contacts'
import { Route as UserAiVoiceRouteImport } from './routes/user.ai-voice'
import { Route as UserAiMovementRouteImport } from './routes/user.ai-movement'
import { Route as UserAiFusionRouteImport } from './routes/user.ai-fusion'
import { Route as AdminVolunteersRouteImport } from './routes/admin.volunteers'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSafeZonesRouteImport } from './routes/admin.safe-zones'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminMonitoringRouteImport } from './routes/admin.monitoring'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as VolunteerIncidentsIndexRouteImport } from './routes/volunteer.incidents.index'
import { Route as VolunteerIncidentsIdRouteImport } from './routes/volunteer.incidents.$id'

const VolunteerRoute = VolunteerRouteImport.update({
  id: '/volunteer',
  path: '/volunteer',
  getParentRoute: () => rootRouteImport,
} as any)
const UserRoute = UserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VolunteerProfileRoute = VolunteerProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => VolunteerRoute,
} as any)
const VolunteerIncidentsRoute = VolunteerIncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => VolunteerRoute,
} as any)
const VolunteerDashboardRoute = VolunteerDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => VolunteerRoute,
} as any)
const VolunteerAlertsRoute = VolunteerAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => VolunteerRoute,
} as any)
const UserSupportTeamsRoute = UserSupportTeamsRouteImport.update({
  id: '/support-teams',
  path: '/support-teams',
  getParentRoute: () => UserRoute,
} as any)
const UserSosRoute = UserSosRouteImport.update({
  id: '/sos',
  path: '/sos',
  getParentRoute: () => UserRoute,
} as any)
const UserSafeZonesRoute = UserSafeZonesRouteImport.update({
  id: '/safe-zones',
  path: '/safe-zones',
  getParentRoute: () => UserRoute,
} as any)
const UserProfileRoute = UserProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => UserRoute,
} as any)
const UserPredictiveSafetyRoute = UserPredictiveSafetyRouteImport.update({
  id: '/predictive-safety',
  path: '/predictive-safety',
  getParentRoute: () => UserRoute,
} as any)
const UserLocationRoute = UserLocationRouteImport.update({
  id: '/location',
  path: '/location',
  getParentRoute: () => UserRoute,
} as any)
const UserHistoryRoute = UserHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => UserRoute,
} as any)
const UserDashboardRoute = UserDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => UserRoute,
} as any)
const UserContactsRoute = UserContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => UserRoute,
} as any)
const UserAiVoiceRoute = UserAiVoiceRouteImport.update({
  id: '/ai-voice',
  path: '/ai-voice',
  getParentRoute: () => UserRoute,
} as any)
const UserAiMovementRoute = UserAiMovementRouteImport.update({
  id: '/ai-movement',
  path: '/ai-movement',
  getParentRoute: () => UserRoute,
} as any)
const UserAiFusionRoute = UserAiFusionRouteImport.update({
  id: '/ai-fusion',
  path: '/ai-fusion',
  getParentRoute: () => UserRoute,
} as any)
const AdminVolunteersRoute = AdminVolunteersRouteImport.update({
  id: '/volunteers',
  path: '/volunteers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSafeZonesRoute = AdminSafeZonesRouteImport.update({
  id: '/safe-zones',
  path: '/safe-zones',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMonitoringRoute = AdminMonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const VolunteerIncidentsIndexRoute = VolunteerIncidentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VolunteerIncidentsRoute,
} as any)
const VolunteerIncidentsIdRoute = VolunteerIncidentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => VolunteerIncidentsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/user': typeof UserRouteWithChildren
  '/volunteer': typeof VolunteerRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/monitoring': typeof AdminMonitoringRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/safe-zones': typeof AdminSafeZonesRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/volunteers': typeof AdminVolunteersRoute
  '/user/ai-fusion': typeof UserAiFusionRoute
  '/user/ai-movement': typeof UserAiMovementRoute
  '/user/ai-voice': typeof UserAiVoiceRoute
  '/user/contacts': typeof UserContactsRoute
  '/user/dashboard': typeof UserDashboardRoute
  '/user/history': typeof UserHistoryRoute
  '/user/location': typeof UserLocationRoute
  '/user/predictive-safety': typeof UserPredictiveSafetyRoute
  '/user/profile': typeof UserProfileRoute
  '/user/safe-zones': typeof UserSafeZonesRoute
  '/user/sos': typeof UserSosRoute
  '/user/support-teams': typeof UserSupportTeamsRoute
  '/volunteer/alerts': typeof VolunteerAlertsRoute
  '/volunteer/dashboard': typeof VolunteerDashboardRoute
  '/volunteer/incidents': typeof VolunteerIncidentsRouteWithChildren
  '/volunteer/profile': typeof VolunteerProfileRoute
  '/volunteer/incidents/$id': typeof VolunteerIncidentsIdRoute
  '/volunteer/incidents/': typeof VolunteerIncidentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/user': typeof UserRouteWithChildren
  '/volunteer': typeof VolunteerRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/monitoring': typeof AdminMonitoringRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/safe-zones': typeof AdminSafeZonesRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/volunteers': typeof AdminVolunteersRoute
  '/user/ai-fusion': typeof UserAiFusionRoute
  '/user/ai-movement': typeof UserAiMovementRoute
  '/user/ai-voice': typeof UserAiVoiceRoute
  '/user/contacts': typeof UserContactsRoute
  '/user/dashboard': typeof UserDashboardRoute
  '/user/history': typeof UserHistoryRoute
  '/user/location': typeof UserLocationRoute
  '/user/predictive-safety': typeof UserPredictiveSafetyRoute
  '/user/profile': typeof UserProfileRoute
  '/user/safe-zones': typeof UserSafeZonesRoute
  '/user/sos': typeof UserSosRoute
  '/user/support-teams': typeof UserSupportTeamsRoute
  '/volunteer/alerts': typeof VolunteerAlertsRoute
  '/volunteer/dashboard': typeof VolunteerDashboardRoute
  '/volunteer/profile': typeof VolunteerProfileRoute
  '/volunteer/incidents/$id': typeof VolunteerIncidentsIdRoute
  '/volunteer/incidents': typeof VolunteerIncidentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/user': typeof UserRouteWithChildren
  '/volunteer': typeof VolunteerRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/monitoring': typeof AdminMonitoringRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/safe-zones': typeof AdminSafeZonesRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/volunteers': typeof AdminVolunteersRoute
  '/user/ai-fusion': typeof UserAiFusionRoute
  '/user/ai-movement': typeof UserAiMovementRoute
  '/user/ai-voice': typeof UserAiVoiceRoute
  '/user/contacts': typeof UserContactsRoute
  '/user/dashboard': typeof UserDashboardRoute
  '/user/history': typeof UserHistoryRoute
  '/user/location': typeof UserLocationRoute
  '/user/predictive-safety': typeof UserPredictiveSafetyRoute
  '/user/profile': typeof UserProfileRoute
  '/user/safe-zones': typeof UserSafeZonesRoute
  '/user/sos': typeof UserSosRoute
  '/user/support-teams': typeof UserSupportTeamsRoute
  '/volunteer/alerts': typeof VolunteerAlertsRoute
  '/volunteer/dashboard': typeof VolunteerDashboardRoute
  '/volunteer/incidents': typeof VolunteerIncidentsRouteWithChildren
  '/volunteer/profile': typeof VolunteerProfileRoute
  '/volunteer/incidents/$id': typeof VolunteerIncidentsIdRoute
  '/volunteer/incidents/': typeof VolunteerIncidentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/register'
    | '/user'
    | '/volunteer'
    | '/admin/dashboard'
    | '/admin/monitoring'
    | '/admin/reports'
    | '/admin/safe-zones'
    | '/admin/users'
    | '/admin/volunteers'
    | '/user/ai-fusion'
    | '/user/ai-movement'
    | '/user/ai-voice'
    | '/user/contacts'
    | '/user/dashboard'
    | '/user/history'
    | '/user/location'
    | '/user/predictive-safety'
    | '/user/profile'
    | '/user/safe-zones'
    | '/user/sos'
    | '/user/support-teams'
    | '/volunteer/alerts'
    | '/volunteer/dashboard'
    | '/volunteer/incidents'
    | '/volunteer/profile'
    | '/volunteer/incidents/$id'
    | '/volunteer/incidents/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/login'
    | '/register'
    | '/user'
    | '/volunteer'
    | '/admin/dashboard'
    | '/admin/monitoring'
    | '/admin/reports'
    | '/admin/safe-zones'
    | '/admin/users'
    | '/admin/volunteers'
    | '/user/ai-fusion'
    | '/user/ai-movement'
    | '/user/ai-voice'
    | '/user/contacts'
    | '/user/dashboard'
    | '/user/history'
    | '/user/location'
    | '/user/predictive-safety'
    | '/user/profile'
    | '/user/safe-zones'
    | '/user/sos'
    | '/user/support-teams'
    | '/volunteer/alerts'
    | '/volunteer/dashboard'
    | '/volunteer/profile'
    | '/volunteer/incidents/$id'
    | '/volunteer/incidents'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/register'
    | '/user'
    | '/volunteer'
    | '/admin/dashboard'
    | '/admin/monitoring'
    | '/admin/reports'
    | '/admin/safe-zones'
    | '/admin/users'
    | '/admin/volunteers'
    | '/user/ai-fusion'
    | '/user/ai-movement'
    | '/user/ai-voice'
    | '/user/contacts'
    | '/user/dashboard'
    | '/user/history'
    | '/user/location'
    | '/user/predictive-safety'
    | '/user/profile'
    | '/user/safe-zones'
    | '/user/sos'
    | '/user/support-teams'
    | '/volunteer/alerts'
    | '/volunteer/dashboard'
    | '/volunteer/incidents'
    | '/volunteer/profile'
    | '/volunteer/incidents/$id'
    | '/volunteer/incidents/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  UserRoute: typeof UserRouteWithChildren
  VolunteerRoute: typeof VolunteerRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/volunteer': {
      id: '/volunteer'
      path: '/volunteer'
      fullPath: '/volunteer'
      preLoaderRoute: typeof VolunteerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user': {
      id: '/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof UserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/volunteer/profile': {
      id: '/volunteer/profile'
      path: '/profile'
      fullPath: '/volunteer/profile'
      preLoaderRoute: typeof VolunteerProfileRouteImport
      parentRoute: typeof VolunteerRoute
    }
    '/volunteer/incidents': {
      id: '/volunteer/incidents'
      path: '/incidents'
      fullPath: '/volunteer/incidents'
      preLoaderRoute: typeof VolunteerIncidentsRouteImport
      parentRoute: typeof VolunteerRoute
    }
    '/volunteer/dashboard': {
      id: '/volunteer/dashboard'
      path: '/dashboard'
      fullPath: '/volunteer/dashboard'
      preLoaderRoute: typeof VolunteerDashboardRouteImport
      parentRoute: typeof VolunteerRoute
    }
    '/volunteer/alerts': {
      id: '/volunteer/alerts'
      path: '/alerts'
      fullPath: '/volunteer/alerts'
      preLoaderRoute: typeof VolunteerAlertsRouteImport
      parentRoute: typeof VolunteerRoute
    }
    '/user/support-teams': {
      id: '/user/support-teams'
      path: '/support-teams'
      fullPath: '/user/support-teams'
      preLoaderRoute: typeof UserSupportTeamsRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/sos': {
      id: '/user/sos'
      path: '/sos'
      fullPath: '/user/sos'
      preLoaderRoute: typeof UserSosRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/safe-zones': {
      id: '/user/safe-zones'
      path: '/safe-zones'
      fullPath: '/user/safe-zones'
      preLoaderRoute: typeof UserSafeZonesRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/profile': {
      id: '/user/profile'
      path: '/profile'
      fullPath: '/user/profile'
      preLoaderRoute: typeof UserProfileRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/predictive-safety': {
      id: '/user/predictive-safety'
      path: '/predictive-safety'
      fullPath: '/user/predictive-safety'
      preLoaderRoute: typeof UserPredictiveSafetyRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/location': {
      id: '/user/location'
      path: '/location'
      fullPath: '/user/location'
      preLoaderRoute: typeof UserLocationRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/history': {
      id: '/user/history'
      path: '/history'
      fullPath: '/user/history'
      preLoaderRoute: typeof UserHistoryRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/dashboard': {
      id: '/user/dashboard'
      path: '/dashboard'
      fullPath: '/user/dashboard'
      preLoaderRoute: typeof UserDashboardRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/contacts': {
      id: '/user/contacts'
      path: '/contacts'
      fullPath: '/user/contacts'
      preLoaderRoute: typeof UserContactsRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/ai-voice': {
      id: '/user/ai-voice'
      path: '/ai-voice'
      fullPath: '/user/ai-voice'
      preLoaderRoute: typeof UserAiVoiceRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/ai-movement': {
      id: '/user/ai-movement'
      path: '/ai-movement'
      fullPath: '/user/ai-movement'
      preLoaderRoute: typeof UserAiMovementRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/ai-fusion': {
      id: '/user/ai-fusion'
      path: '/ai-fusion'
      fullPath: '/user/ai-fusion'
      preLoaderRoute: typeof UserAiFusionRouteImport
      parentRoute: typeof UserRoute
    }
    '/admin/volunteers': {
      id: '/admin/volunteers'
      path: '/volunteers'
      fullPath: '/admin/volunteers'
      preLoaderRoute: typeof AdminVolunteersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/safe-zones': {
      id: '/admin/safe-zones'
      path: '/safe-zones'
      fullPath: '/admin/safe-zones'
      preLoaderRoute: typeof AdminSafeZonesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/monitoring': {
      id: '/admin/monitoring'
      path: '/monitoring'
      fullPath: '/admin/monitoring'
      preLoaderRoute: typeof AdminMonitoringRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/volunteer/incidents/': {
      id: '/volunteer/incidents/'
      path: '/'
      fullPath: '/volunteer/incidents/'
      preLoaderRoute: typeof VolunteerIncidentsIndexRouteImport
      parentRoute: typeof VolunteerIncidentsRoute
    }
    '/volunteer/incidents/$id': {
      id: '/volunteer/incidents/$id'
      path: '/$id'
      fullPath: '/volunteer/incidents/$id'
      preLoaderRoute: typeof VolunteerIncidentsIdRouteImport
      parentRoute: typeof VolunteerIncidentsRoute
    }
  }
}

interface AdminRouteChildren {
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminMonitoringRoute: typeof AdminMonitoringRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSafeZonesRoute: typeof AdminSafeZonesRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminVolunteersRoute: typeof AdminVolunteersRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDashboardRoute: AdminDashboardRoute,
  AdminMonitoringRoute: AdminMonitoringRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSafeZonesRoute: AdminSafeZonesRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminVolunteersRoute: AdminVolunteersRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface UserRouteChildren {
  UserAiFusionRoute: typeof UserAiFusionRoute
  UserAiMovementRoute: typeof UserAiMovementRoute
  UserAiVoiceRoute: typeof UserAiVoiceRoute
  UserContactsRoute: typeof UserContactsRoute
  UserDashboardRoute: typeof UserDashboardRoute
  UserHistoryRoute: typeof UserHistoryRoute
  UserLocationRoute: typeof UserLocationRoute
  UserPredictiveSafetyRoute: typeof UserPredictiveSafetyRoute
  UserProfileRoute: typeof UserProfileRoute
  UserSafeZonesRoute: typeof UserSafeZonesRoute
  UserSosRoute: typeof UserSosRoute
  UserSupportTeamsRoute: typeof UserSupportTeamsRoute
}

const UserRouteChildren: UserRouteChildren = {
  UserAiFusionRoute: UserAiFusionRoute,
  UserAiMovementRoute: UserAiMovementRoute,
  UserAiVoiceRoute: UserAiVoiceRoute,
  UserContactsRoute: UserContactsRoute,
  UserDashboardRoute: UserDashboardRoute,
  UserHistoryRoute: UserHistoryRoute,
  UserLocationRoute: UserLocationRoute,
  UserPredictiveSafetyRoute: UserPredictiveSafetyRoute,
  UserProfileRoute: UserProfileRoute,
  UserSafeZonesRoute: UserSafeZonesRoute,
  UserSosRoute: UserSosRoute,
  UserSupportTeamsRoute: UserSupportTeamsRoute,
}

const UserRouteWithChildren = UserRoute._addFileChildren(UserRouteChildren)

interface VolunteerIncidentsRouteChildren {
  VolunteerIncidentsIdRoute: typeof VolunteerIncidentsIdRoute
  VolunteerIncidentsIndexRoute: typeof VolunteerIncidentsIndexRoute
}

const VolunteerIncidentsRouteChildren: VolunteerIncidentsRouteChildren = {
  VolunteerIncidentsIdRoute: VolunteerIncidentsIdRoute,
  VolunteerIncidentsIndexRoute: VolunteerIncidentsIndexRoute,
}

const VolunteerIncidentsRouteWithChildren =
  VolunteerIncidentsRoute._addFileChildren(VolunteerIncidentsRouteChildren)

interface VolunteerRouteChildren {
  VolunteerAlertsRoute: typeof VolunteerAlertsRoute
  VolunteerDashboardRoute: typeof VolunteerDashboardRoute
  VolunteerIncidentsRoute: typeof VolunteerIncidentsRouteWithChildren
  VolunteerProfileRoute: typeof VolunteerProfileRoute
}

const VolunteerRouteChildren: VolunteerRouteChildren = {
  VolunteerAlertsRoute: VolunteerAlertsRoute,
  VolunteerDashboardRoute: VolunteerDashboardRoute,
  VolunteerIncidentsRoute: VolunteerIncidentsRouteWithChildren,
  VolunteerProfileRoute: VolunteerProfileRoute,
}

const VolunteerRouteWithChildren = VolunteerRoute._addFileChildren(
  VolunteerRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  UserRoute: UserRouteWithChildren,
  VolunteerRoute: VolunteerRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
